### ISSUE TITLE
how to interface this with Redis that doesn't use the default localhost location

### ISSUE THREAD

**Issue by kasperkamperman** [jeroenvisser101/LeakyBucket#10]
Hi, 
Maybe a n00b question, but I can't make this interface with a Redis case that doesn't use the default Redis location ([tcp://127.0.0.1:6379]). 

I try to pass a Redis client like this:
```php
$redis = new Predis\Client(array(
     'host'     => '10.0.22.1', 
    'port'     => '20700',
    'password' => 'mypass', 
));

$storage = new RedisStorage($redis);
```

This give me the following error:
```
__construct() must be an instance of LeakyBucket\Storage\Helpers\RedisClient or null, instance of Predis\Client given
```

However the RedisClient helper extends Client, so I don't exactly get why it doesn't work.

I also tried your helper and included the namespace. However that throws `Uncaught Error: Class 'RedisClient' not found`

```php
ini_set('display_errors', '1');
ini_set('error_reporting', E_ALL);

require_once("vendor/autoload.php"); 

use Predis\Client;
use LeakyBucket\LeakyBucket;
use LeakyBucket\Storage\RedisStorage;
use LeakyBucket\Storage\Helpers;

$redis = new RedisClient(array(
    'host'     => '10.0.22.1', 
    'port'     => '20700',
    'password' => 'mypass', 
));

// Define which storage to use
$storage = new RedisStorage($redis);

// Define the bucket
$settings = [
    'capacity' => 10,
    'leak'     => 1
];

// Create the bucket
$bucket = new LeakyBucket('example-bucket', $storage, $settings);
```

I hope you can help. Probably I overlook something simple, I'm not really a PHP expert (especially not regarding namespaces and objects). 

Thanks in advance for your reply and time.

**Comment by jeroenvisser101** [comment]
Hey @kasperkamperman,

To be honest, I wouldn't really know. It's been over 2 years since I wrote my last line of PHP (and 4 years since the last significant update of this project), but looking at the code, my guess is that you need to change this:

```php
use Predis\Client;
use LeakyBucket\LeakyBucket;
use LeakyBucket\Storage\RedisStorage;
use LeakyBucket\Storage\Helpers;
```

to

```php
use LeakyBucket\LeakyBucket;
use LeakyBucket\Storage\RedisStorage;
use LeakyBucket\Storage\Helpers\RedisClient;
```

**Comment by kasperkamperman** [comment]
Thanks! That did the trick.
