### ISSUE TITLE
Please perform a v0.1.5 release

### ISSUE THREAD

**Issue by jameshulse** [jeroenvisser101/LeakyBucket#8]
The current v0.1.4 package contains a number of bugs which look like they have been subsequently fixed but no release was ever made.

Can you please perform a release so that composer will pick up the latest version by deafult.

Thanks!

**Comment by jeroenvisser101** [comment]
Hi @jameshulse. I've not coded PHP in a long time. I'm happy to add you as a collaborator or something if you want to take over maintenance for this project.

**Comment by jameshulse** [comment]
Hi @jeroenvisser101, thanks for responding! I understand. I saw that you hadn't touched this project for a few years.

We are integrating this library into a commercial product that we are working on so it could be useful for me to be able to perform releases and apple bug fixes / improve testing.

**Comment by jeroenvisser101** [comment]
is your username on packagist also jameshulse?

**Comment by jeroenvisser101** [comment]
I did add a new version just now, but I'm not sure it worked.

**Comment by jameshulse** [comment]
Thanks! Composer has picked up the new version and I can see the fixes are in. My username is the same on packagist (I only just created an account now).

**Comment by jeroenvisser101** [comment]
I added you as a maintainer on Packagist and GitHub. Let me know if there's anything I missed
